spring:
  mvc:
    log-request-details: true
  application:
    name: marketplaceRoiManager
  profiles:
    active:
      - dev

logging:
  level:
    root: INFO


api:
  allegro:
    client-id: ${ALLEGRO_CLIENT_ID}
    client-secret: ${ALLEGRO_CLIENT_SECRET}
    scope: allegro:api:profile:read
